#ifndef COMPARISON_H
#define COMPARISON_H

#include<iostream>
#include<vector>
#include<string>
#include<mutex>
#include"FileHandler.h"
#include"DataCleanser.h"
#include"Resources.h"
#include"Patterns.h"

using namespace std;

class Comparison
{
public:
	vector<string> passwordSubStrings;
	vector<Resources::patternStructure> results1;

	vector<string> passwordsList;//VECTOR TO STORE PASSWORDS OF SINGLE FILES
	vector<string> emailsList;//VECTOR TO STORE EMAILS OF SINGLE FILES
	vector<string> emailNamesList;//VECTOR TO STORE EMAIL_NAMES EXTRACTED FROM EMAILS VECTOR
	vector<string> websitesList;//VECTOR TO STORE WEBSITES EXTRACTED FROM EMAILS VECTOR
	vector<string> rawData;//TO STORE TEMP DATA FOR FUTURE PROCESSING
	vector<Resources::patternStructure> results;//FINAL OUTPUT OF ALL THIS PROCESS WILL STORED IN THIS VECTOR

	/*
		HERE DATA WILL BE LOADED INTO A VECTOR ACCORDING TO RESERVESIZE VALUE
	*/
	void load_data(vector<string>::iterator beginIt, vector<string>::iterator endIt, int reserveSize);
	
	/*
		THIS FUNCTION WILL LOWER ALL INCOMING DATA
	*/
	void lower_case_raw_data();

	/*
		DELIMITER IS SEPERATING STRING OF EMAIL AND PASSWORD E.G. ':'
		HERE EMAIL AND PASSWORD WILL BE EXTRACTED OUT AND STORED IN RESPECTIVE VECTORS
		STEP 1. FOR LOOP WILL ITERATE OVER RAWDATA ONE BY ONE
		STEP 2. FIRST WE WILL FIND @ FROM THERE WE WILL FIND DELIMITER. THIS IS FOR AVOIDING
				FRONT PART WHICH CAN INCLUDE ':' DELIMITER
		STEP 3. CONTENT BEFORE DELIMITER AND AFTER DELIMITER WILL BE SEPARATED ON BASIS OF LOCATIONS
	*/
	void extract_email_and_password(string delimiter);

	/*
		HERE WE WILL EXTRACT EMAIL BOTH HALF PART AS EMAIL NAME AND WEBSITE
		STEP 1. FIRST WE WILL FIND @ SYMBOL WHICH CAN BE SEEN AS MIDDLE LOCATION
		STEP 2. CONTENT BEFORE @ AND AFTER @ WILL BE SEPERATED OUT IN TWO STRINGS
		STEP 3. BOTH STRINGS WILL BE STORED IN RESPECTIVE VECTORS
	*/
	void extract_email_names_and_websites();

	/*
		HERE PASSWORD STRING WILL BE COMPARED AGAINST ALL COMMON NAME LISTS
		STEP 1. AN ITERATOR WILL SET ON NAME LIST VECTOR
		STEP 2. WHILE LOOP WILL CHECK IF ANY NAME EXISTS IN PASSWORD STRING
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void name_list_comparison(string password);

	/*
		HERE EMAIL NAME/ FRONT PART OF EMAIL WILL BE COMPARED AGAINST PASSWORD STRING
		STEP 1. FIRST ACCORDING TO PASSWORD NUMBER ITS RESPECTIVE EMAIL FRONT WILL BE CALLED
		STEP 2. IF STATEMENT WILL CHECK IF FRONT PART EXISTS IN PASSWORD OR NOT
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void email_name_list_comparison(string password, vector<string>::iterator& password_it);

	/*
		HERE WEBSITE PART OF EMAIL WILL BE COMPARED AGAINST PASSWORD STRING
		STEP 1. FIRST ACCORDING TO PASSWORD NUMBER ITS RESPECTIVE WEBSITE PART WILL BE CALLED
		STEP 2. IF STATEMENT WILL CHECK IF WEBSITE PART EXISTS IN PASSWORD OR NOT
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void website_list_comparison(string password, vector<string>::iterator& password_it);
	
	/*
		HERE DOB LISTS WILL BE COMPARED AGAINST PASSWORD STRING
		STEP 1. AN ITERATOR WILL SET ON DOB LIST VECTOR
		STEP 2. WHILE LOOP WILL CHECK IF ANY DOB EXISTS IN PASSWORD STRING
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void dob_list_comparison(string password);

	/*
		HERE LOCATION LISTS WILL BE COMPARED AGAINST PASSWORD STRING
		STEP 1. AN ITERATOR WILL SET ON LOCATION LIST VECTOR
		STEP 2. WHILE LOOP WILL CHECK IF ANY LOCATION EXISTS IN PASSWORD STRING
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void location_list_comparison(string password);

	/*
		HERE PASSWORD STRING WILL BE EXAMINED TO TEST IF THEIR ANY MOBILE NUMBER EXISTS
		STEP 1. FOR LOOP WILL ITERATE OVER EVERY CHARACTER OF PASSWORD STRING
		STEP 2. FIRST IF WILL CHECK IF CURRENT CHARACTER IS A DIGIT OR NOT. IF IT IS A DIGIT
				THEN PROGRAM WILL CONTINUE TO FURTHER STATEMENTS ELSE WILL BE CONTINUE TO NEXT CHARACTER.
		STEP 3. SECOND IF WILL CHECK IF PASSWORD HAS ANOTHER 3 CHARACTER AFTER CURRENT CHARACTER
				IF NOT THEN LOOP WILL BE BRAKED
		STEP 4. THIRD IF WILL CHECK  IF ALL THESE 4 CHARACTER INCLUDING CURRENT CHARACTER ARE DIGITS OR NOT.
				IF NOT THEN LOOP WILL BE CONTINUED TO NEXT CHARACTER.
		STEP 5. SECOND FOR LOOP WILL CHECK AFTER THESE 4 CHARACTER INCLUDING CURRENT CHARACTER ARE THERE
				ANYMORE DIGITS ARE PRESENT. IF THERE ARE MORE DIGIT THEN IT WILL CHECK HOW MANY ARE THERE.
		STEP 6. FINALLY RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void mobile_number_comparison(string password);
	
	/*
		HERE COMMON WORDS LISTS WILL BE COMPARED AGAINST PASSWORD STRING
		STEP 1. AN ITERATOR WILL SET ON COMMON WORDS LIST VECTOR
		STEP 2. WHILE LOOP WILL CHECK IF ANY COMMON WORD EXISTS IN PASSWORD STRING
		STEP 3. MAXIMUM 3 COMMON WORDS WILL BE FIND IN A SINGLE PASSWORD STRING (USING IF STATEMENTS)
		STEP 3. IF SO THEN RESULT WILL BE ADDED WITH LOCATION, LENGTH, TAG AND CONTENT
	*/
	void common_word_list_comparison(string password);

	/*
		HERE VECTORS AND OTHER MEMBERS WILL BE CLEARED AND SHRINKED TO RELEASE MEMORY
	*/
	void clear_and_shrink();
};

#endif