#ifndef PATTERN_H
#define PATTERN_H

#include<iostream>
#include<vector>
#include<string>
#include"Resources.h"

using namespace std;

class Patterns
{
public:
	vector<Resources::patternStructure> rawResults;//STORING RAW RESULTS TO MAKE THEM INTO PATTERNS
	vector<vector<Resources::patternStructure>> splittedResults;//REQUIRED IN PATTERN CREATION
	vector<string> output;//PROCESSED OUTPUT / FINAL PATTERNS

	/*
		HERE PROCESSED DATA WILL BE CONVERTED INTO PATTERNS
		STEP 1. SORT DATA
		STEP 2. CALL DIVIDE_PATTERNS() ON DATA TO DIVIDE OVERLAPPING PATTERNS AND ADDRESSING UNDETECTED PART
		STEP 3. SORT DATA ON BASIS OF STRUCT LENGTH ELEMENT
		STEP 4. FORMATTING OUTPUT AND WRITE IT IN A FILE
	*/
	void pattern(string password);

	/*
		THIS FUNCTION TAKES A VECTOR OF TYPE PATTERNSTRUCTURE AND SORT IT
		ON THE BASIS OF ITS LENGTH ELEMENT
	*/
	void sort_vector_struct_on_length(vector<Resources::patternStructure>& x);

	/*
		THIS FUNCTION TAKES A VECTOR OF TYPE PATTERNSTRUCTURE AND SORT IT
		ON THE BASIS OF ITS LOCATION ELEMENT
	*/
	void sort_vector_struct_on_location(vector<Resources::patternStructure>& x);
	
	/*
		HERE A SINGLE PATTERN GET DIVIDED INTO MULTIPLE IF IT OVERLAPPING ITSELF.
		TO ADDRESS UNDETECTED PART UNDETECTED() WILL CALLED AFTER DIVIDING PATTER IN MULTIPLE PATTERNS
		STEP 1. EVERY PART WILL BE TESTED TO VERIFY LOCATION ATTRIBUTE IS OVERLAPPING OR NOT
		STEP 2. IF SO THEN OVERLAPPING PART WILL BE CALLED RECURSIVELY AND CURRENT PART WILL BE STORED.
		STEP 3. THIS WILL END WITH CALLING UNDETECTED() ON ALL THE PATTERNS.
	*/
	void divide_patterns(vector<Resources::patternStructure>& patternVector, string password);

	/*
		THIS FUNCTION TAKES SPLITTEDRESULTS AND ANALYSE THEIR UNDETECTED PART TO ADD UNDETECTED TAG.
		STEP 1. EVERY PATTERN WILL GO THROUGH FOR LOOP ONE BY ONE
		STEP 2. FOR LOOP HAS 3 IF STATEMENTS TO ADDRESS FRONT - MIDDLE - END PART OF PATTERN
		STEP 3. FIRST IF WILL CHECK IF LOCATION 0 IS AN UNDETECTED PART OR NOT
		STEP 4. SECOND IF WILL RUN A LOOP UNTIL LAST DETECTED PART TO CHECK IF THERE IS AN UNDETECTED
				PART IN MIDDLE
		STEP 5. THIRD IF WILL CHECK IF END OF PASSWORD IS UNDETECTED PART OR NOT
		STEP 6. IF ANY PART OF PASSWORD IS FOUND TO BE UNDETECTED THAN A TAG WILL WE ADDED TO THAT
				LOCATION.
	*/
	void undetected(string password);

	/*
		THIS FUNCTION STARTS A MUTEX TO INSERT OUTPUT OF THIS THREAD TO MAIN RESOURCE OUTPUT CONTAINER
	*/
	void insert_output();

	/*
		THIS FUNCTION WILL CLEAR AND SHRINK VECTORS AND OTHER MEMBERS
	*/
	void clear_and_shrink();
};

#endif