#ifndef STATSGENERATOR_H
#define STATSGENERATOR_H

#include<iostream>
#include<fstream>
#include<thread>
#include<vector>
#include<deque>
#include<set>
#include<string>
#include<algorithm>
#include<mutex>
#include<unordered_map>

using namespace std;

class StatsGenerator
{
public:
	/*
		FUNCTION TO LOAD PROCESSED FILES.
		STEP 1. MAKE A ITERATOR FOR MAP, TEMP OBJECT OF PATTERN STRUCTURE AND TEMP DEQUE TO INITIALIZE MAP
		STEP 2. A WHILE TO ITERATE OVER STORED PATTERNS
		STEP 3. IF THERE IS A DELIMITER/DIVIDER THEN STORE PATTERN STRING, POPULARITY AND A 
				EMPTY DEQUE FOR PATTERN DATA.
		STEP 4. CLEAR AND SHRINK STORED PATTERN MAP
	*/
	static void load_stored_patterns(deque<string>& storedPatterns);

	/*
		STEP 1. DECLARE A ITERATOR FOR MAIN MAP AND A WHILE LOOP TO ITERATE
		STEP 2. CHECK IF NEW DATA IS ADDED INTO MAIN MAP FOR RESPECTIVE PATTERN( DEQUE SIZE > 0 )
		STEP 3. IF SO THEN CHECK IF THAT CATEGORY HAS A ADDRESS FOR DATA FILE
		STEP 4. IF SO THEN APPEND DATA FILE WITH NEW DATA ELSE CREATE A NEW FILE WITH NEW DATA.
	*/
	static void write_pattern_statstics_files();

	/*
		THIS FUNCTION EXTRACTS FILE NAME BY REMOVING EXTENSION OF FILES
	*/
	static string split_filename(const string str);

	/*
		FUNCTION TO WRITE CATEGORIZED PATTENS INTO A SINGLE FILE WITH ADDRESSES OF THEIR RESPECTIVE DATA FILES.
		STEP 1. DECLARE DEQUE FOR PATTERN AND ADDRESS AND A ITERATOR FOR MAIN MAP
		STEP 2. WHILE LOOP TO ITERATE OVER MAP
		STEP 3. ADD PATTERN, ADDRESS AND POPULARITY TO DEQUE AND FINALLY AFTER LOOP WRITE THAT IN A FILE.
		STEP 4. CLEAR AND SHRINK VARIABLES.
	*/
	static void write_key_patterns();

	//THREAD SAFE MEMBERS
	//UNORDERED MAP TO STORE PATTERNS AND THEIR DATA TEMPORARILY
	unordered_map<string, set<string>> statsResults;
	
	/*
		FUNCTION TO CLASSIFY PATTERNS, SO THAT SAME PATTERN HAVE A SINGLE FILE FOR ITS DATA.
		STEP 1. DECLARE VARIABLES- TEMP DEQUE AND A MAP WITH ITERATORS 
		STEP 2. READ FILE CONTENT INTO TEMP DEQUE AND ITERATE OVER TEMPDEQUE WITH WHILE LOOP
		STEP 3. FIND FIRST DELIMITER/DIVIDE IN STRING WHICH WILL DENOTE PATTERN STRING
		STEP 4. CHECK IF IT ALREADY EXIST IN TEMP MAP OF PATTERNS CATEGORIES
		STEP 5. IF SO, THEN ADD PATTERN DATA TO FOUND CATEGORY ELSE CREATE A NEW ONE.
		STEP 6. CLEAR AND SHRINK ALL VARIABLES. 
	*/
	void patterns_classifier(string filePath);

	/*
		FUNCTION TO STORE TEMP MAP CATEGORIES INTO FINAL MAIN MAP CATEGORIES
		STEP 1. DECLARE ITERATOR FOR TEMP MAP AND MAIN MAP
		STEP 2. START AND MUTEX AND LOCK GUARD FOR THREAD SAFE EXECUTION
		STEP 3. WHILE LOOP TO ITERATE OVER TEMP MAP
		STEP 4. CHECK IF TEMP MAP PATTERN CATEGORY EXIST IN MAIN MAP
		STEP 5. IF SO THEN ADD TEMP MAP CATEGORY DATA TO MAIN MAP CATEGORY DATA 
		STEP 6. ELSE CREATE A NEW CATEGORY IN MAIN MAP
		STEP 7. CLEAR AND SHRINK VARIABLES 
	*/
	void store_classified_patterns();

	/*
		FUNCTION TO CLEAR AND SHRINK CONTAINERS BELONG TO STATS GENERATOR CLASS
	*/
	void clear_and_shrink();


	/*
		FUNCTION TO REMOVE COMMON REDUNDANT PATTERN DATA FROM STORED
		STEP 1. CHECK IF TOTAL UNIQUE PATTERN DATA FILES ARE SMALLER OR BIGGER THEN
				SPECIFIED NUMBER OF THREADS
		STEP 2. IF BIGGER THEN DIVIDE FILES ADDRESS EQUALLY TO THREADS AND REMAINDER
				SHOULD GO WITH ANOTHER LAST THREAD
		STEP 3. CALL HELPER FUNCTION ON EACH THREAD TO PERFORM OPERATION
		STEP 4. CLEAR CONTAINERS
	*/
	static void remove_redundant_pattern_data(int numberOfThreads);

	/*
		HELPER FUNCTION TO REMOVE REDUNDANT DATA (THREAD SAFE FUNCTION)
		STEP 1.	LOOP ON EACH FILE ADDRESS
		STEP 2. FIND FILE NAME(PATTERN) IN MAIN PATTERN STATS MAP
		STEP 3. READ UNIQUE PATTERN FILE DATA
		STEP 4. REMOVE REDUNDANT/DUPLICATE DATA ENTRIES
		STEP 5. UPDATE PATTERN POPULARITY IN MAIN PATTERN STATS MAP
		STEP 6. WRITE UNIQUE PATTERN FILE DATA
		STEP 7. CLEAR ADN SHRINK CONTAINERS
	*/
	static void helper_to_remove_redundant_data(StatsGenerator& threadObj);

	//VECTOR TO STORE ADDRESS OF UNIQUE PATTERN DATA FILES
	vector<string> uniquePatternFiles;
};

#endif // !STATSGENERATOR_H